ALTER USER hr ACCOUNT UNLOCK IDENTIFIED BY hr;

--------------------------------------------------------
--  File created - Thursday-July-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MUNICIPALITIES
--------------------------------------------------------

  CREATE TABLE "HR"."MUNICIPALITIES" 
   (	"CPRO" NUMBER(4,0), 
	"CMUN" NUMBER(5,0), 
	"DC" NUMBER(3,0), 
	"MUNICIPALITY" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VRANGES
--------------------------------------------------------

  CREATE TABLE "HR"."VRANGES" 
   (	"VTYPE_ID" NUMBER(3,0), 
	"VRANGE_ID" NUMBER(3,0), 
	"DESCRIPTION" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VT_TARIFFS
--------------------------------------------------------

  CREATE TABLE "HR"."VT_TARIFFS" 
   (	"REG_ID" NUMBER(3,0), 
	"PRO_ID" NUMBER(4,0), 
	"MUN_ID" NUMBER(4,0), 
	"VTYPE_ID" NUMBER(3,0), 
	"VRANGE_ID" NUMBER(3,0), 
	"YEAR" NUMBER(6,0), 
	"PRICE" NUMBER(7,2), 
	"CURRENCY" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VTYPES
--------------------------------------------------------

  CREATE TABLE "HR"."VTYPES" 
   (	"ID" NUMBER(3,0), 
	"DESCRIPTION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MUNICIPALITIES
SET DEFINE OFF;
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,1,7,'ALAMEDA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,2,2,'ALCAUCIN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,3,8,'ALFARNATE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,4,3,'ALFARNATEJO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,5,6,'ALGARROBO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,6,9,'ALGATOCIN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,7,5,'ALHAURIN DE LA TORRE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,8,1,'ALHAURIN EL GRANDE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,9,4,'ALMACHAR');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,10,8,'ALMARGEN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,11,5,'ALMOGIA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,12,0,'ALORA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,13,6,'ALOZAINA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,14,1,'ALPANDEIRE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,15,4,'ANTEQUERA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,16,7,'ARCHEZ');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,17,3,'ARCHIDONA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,18,9,'ARDALES');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,19,2,'ARENAS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,20,6,'ARRIATE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,21,3,'ATAJATE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,22,8,'BENADALID');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,23,4,'BENAHAVIS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,24,9,'BENALAURIA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,25,2,'BENALMADENA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,26,5,'BENAMARGOSA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,27,1,'BENAMOCARRA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,28,7,'BENAOJAN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,29,0,'BENARRABA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,30,4,'BORGE, EL');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,31,1,'BURGO, EL');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,32,6,'CAMPILLOS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,33,2,'CANILLAS DE ACEITUNO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,34,7,'CANILLAS DE ALBAIDA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,35,0,'CANETE LA REAL');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,36,3,'CARRATRACA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,37,9,'CARTAJIMA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,38,5,'CARTAMA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,39,8,'CASABERMEJA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,40,2,'CASARABONELA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,41,9,'CASARES');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,42,4,'COIN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,43,0,'COLMENAR');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,44,5,'COMARES');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,45,8,'COMPETA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,46,1,'CORTES DE LA FRONTERA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,47,7,'CUEVAS BAJAS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,49,6,'CUEVAS DE SAN MARCOS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,48,3,'CUEVAS DEL BECERRO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,50,9,'CUTAR');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,51,6,'ESTEPONA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,52,1,'FARAJAN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,53,7,'FRIGILIANA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,54,2,'FUENGIROLA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,55,5,'FUENTE DE PIEDRA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,56,8,'GAUCIN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,57,4,'GENALGUACIL');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,58,0,'GUARO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,59,3,'HUMILLADERO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,60,7,'IGUALEJA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,61,4,'ISTAN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,62,9,'IZNATE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,63,5,'JIMERA DE LIBAR');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,64,0,'JUBRIQUE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,65,3,'JUZCAR');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,66,6,'MACHARAVIAYA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,67,2,'MALAGA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,68,8,'MANILVA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,69,1,'MARBELLA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,70,5,'MIJAS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,71,2,'MOCLINEJO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,72,7,'MOLLINA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,73,3,'MONDA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,903,9,'MONTECORTO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,74,8,'MONTEJAQUE');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,75,1,'NERJA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,76,4,'OJEN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,77,0,'PARAUTA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,79,9,'PERIANA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,80,3,'PIZARRA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,81,0,'PUJERRA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,82,5,'RINCON DE LA VICTORIA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,83,1,'RIOGORDO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,84,6,'RONDA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,85,9,'SALARES');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,86,2,'SAYALONGA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,87,8,'SEDELLA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,904,4,'SERRATO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,88,4,'SIERRA DE YEGUAS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,89,7,'TEBA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,90,1,'TOLOX');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,901,8,'TORREMOLINOS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,91,8,'TORROX');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,92,3,'TOTALAN');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,93,9,'VALLE DE ABDALAJIS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,94,4,'VELEZ-MALAGA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,95,7,'VILLANUEVA DE ALGAIDAS');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,902,3,'VILLANUEVA DE LA CONCEPCION');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,98,2,'VILLANUEVA DE TAPIA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,96,0,'VILLANUEVA DEL ROSARIO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,97,6,'VILLANUEVA DEL TRABUCO');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,99,5,'VINUELA');
INSERT INTO HR.MUNICIPALITIES (CPRO,CMUN,DC,MUNICIPALITY) VALUES (29,100,9,'YUNQUERA');
REM INSERTING into HR.VRANGES
SET DEFINE OFF;
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (1,1,'De 0 H.P. a 7.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (1,2,'De 8 H.P. a 11.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (1,3,'De 12 H.P. a 15.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (1,4,'De 16 H.P. a 19.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (1,5,'De 20 H.P. a 999.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (2,1,'De 0 PZ. a 20 PZ.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (2,2,'De 21 PZ. a 50 PZ.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (2,3,'De 51 PZ. a 9999 PZ.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (3,1,'De 0 KG. a 999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (3,2,'De 1000 KG. a 2999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (3,3,'De 3000 KG. a 9999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (3,4,'De 10000 KG. a 999999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (4,1,'De 0 H.P. a 15.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (4,2,'De 16 H.P. a 25 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (4,3,'De 25.01 H.P. a 9999.99 H.P.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (5,1,'De 0 KG. a 750 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (5,2,'De 751 KG. a 999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (5,3,'De 1000 KG. a 2999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (5,4,'De 3000 KG. a 999999 KG.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (6,1,'De 0 C.C. a 125 C.C.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (6,2,'De 126 C.C. a 250 C.C.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (6,3,'De 251 C.C. a 500 C.C.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (6,4,'De 501 C.C. a 1000 C.C.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (6,5,'De 1001 C.C. a 999999 C.C.');
Insert into HR.VRANGES (VTYPE_ID,VRANGE_ID,DESCRIPTION) values (7,1,'De 0 C.C. a 999999 C.C.');
REM INSERTING into HR.VT_TARIFFS
SET DEFINE OFF;
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,1,1,2017,21.45,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,1,2,2017,57.94,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,1,3,2017,122.3,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,1,4,2017,152.34,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,1,5,2017,190.4,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,2,1,2017,141.61,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,2,2,2017,201.69,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,2,3,2017,252.11,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,3,1,2017,71.88,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,3,2,2017,141.61,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,3,3,2017,201.69,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,3,4,2017,252.11,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,4,1,2017,30.04,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,4,2,2017,47.21,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,4,3,2017,141.61,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,5,1,2017,0,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,5,2,2017,30.04,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,5,3,2017,47.21,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,5,4,2017,141.61,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,6,1,2017,8.84,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,6,2,2017,15.14,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,6,3,2017,30.3,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,6,4,2017,60.58,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,6,5,2017,121.16,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,7,7,1,2017,8.84,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,1,1,2017,17.68,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,1,2,2017,51.4,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,1,3,2017,116.25,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,1,4,2017,154.47,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,1,5,2017,205.12,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,2,1,2017,125.64,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,2,2,2017,178.94,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,2,3,2017,223.68,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,3,1,2017,64.59,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,3,2,2017,125.64,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,3,3,2017,178.94,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,3,4,2017,223.68,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,4,1,2017,26.66,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,4,2,2017,41.89,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,4,3,2017,125.64,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,5,1,2017,0,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,5,2,2017,26.66,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,5,3,2017,41.89,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,5,4,2017,125.64,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,6,1,2017,6.67,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,6,2,2017,12.24,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,6,3,2017,26.11,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,6,4,2017,55.47,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,6,5,2017,117.47,'EUR');
Insert into HR.VT_TARIFFS (REG_ID,PRO_ID,MUN_ID,VTYPE_ID,VRANGE_ID,YEAR,PRICE,CURRENCY) values (1,29,69,7,1,2017,6.2,'EUR');
REM INSERTING into HR.VTYPES
SET DEFINE OFF;
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (1,'TURISMOS');
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (2,'AUTOBUSES');
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (3,'CAMIONES');
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (4,'TRACTORES');
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (5,'REMOLQUES Y SEMIREMOLQUES');
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (6,'OTROS VEHICULOS');
INSERT INTO HR.VTYPES (ID,DESCRIPTION) VALUES (7,'CICLOMOTORES');
--------------------------------------------------------
--  DDL for Index MUNICIPALITIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MUNICIPALITIES_PK" ON "HR"."MUNICIPALITIES" ("CPRO", "CMUN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VRANGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."VRANGES_PK" ON "HR"."VRANGES" ("VTYPE_ID", "VRANGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VT_TARIFFS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."VT_TARIFFS_PK" ON "HR"."VT_TARIFFS" ("REG_ID", "PRO_ID", "MUN_ID", "VTYPE_ID", "VRANGE_ID", "YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VTYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."VTYPES_PK" ON "HR"."VTYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MUNICIPALITIES
--------------------------------------------------------

  ALTER TABLE "HR"."MUNICIPALITIES" ADD CONSTRAINT "MUNICIPALITIES_PK" PRIMARY KEY ("CPRO", "CMUN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MUNICIPALITIES" MODIFY ("MUNICIPALITY" NOT NULL ENABLE);
  ALTER TABLE "HR"."MUNICIPALITIES" MODIFY ("DC" NOT NULL ENABLE);
  ALTER TABLE "HR"."MUNICIPALITIES" MODIFY ("CMUN" NOT NULL ENABLE);
  ALTER TABLE "HR"."MUNICIPALITIES" MODIFY ("CPRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VRANGES
--------------------------------------------------------

  ALTER TABLE "HR"."VRANGES" ADD CONSTRAINT "VRANGES_PK" PRIMARY KEY ("VTYPE_ID", "VRANGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."VRANGES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HR"."VRANGES" MODIFY ("VRANGE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."VRANGES" MODIFY ("VTYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VT_TARIFFS
--------------------------------------------------------

  ALTER TABLE "HR"."VT_TARIFFS" ADD CONSTRAINT "VT_TARIFFS_PK" PRIMARY KEY ("REG_ID", "PRO_ID", "MUN_ID", "VTYPE_ID", "VRANGE_ID", "YEAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("VRANGE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("VTYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("MUN_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("PRO_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."VT_TARIFFS" MODIFY ("REG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VTYPES
--------------------------------------------------------

  ALTER TABLE "HR"."VTYPES" ADD CONSTRAINT "VTYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."VTYPES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HR"."VTYPES" MODIFY ("ID" NOT NULL ENABLE);

commit;

create or replace PROCEDURE "HR".GET_VTARIFFS_RS (p_pro_id_in IN NUMBER, p_mun_id_in IN NUMBER, p_year_in IN NUMBER, p_mun_desc_out OUT VARCHAR2, p_recordset OUT SYS_REFCURSOR)
   AS
   BEGIN
     SELECT MUNICIPALITY
      INTO p_mun_desc_out
      FROM  MUNICIPALITIES WHERE CMUN = p_mun_id_in;

     OPEN p_recordset FOR
       SELECT M.MUNICIPALITY, T.DESCRIPTION AS "VEHICLE TYPE", R.DESCRIPTION AS "TAX RANGE", TF."YEAR", TF.PRICE, TF.CURRENCY
       FROM   "HR"."VT_TARIFFS" TF, "HR"."MUNICIPALITIES" M, "HR"."VTYPES"  T,  "HR"."VRANGES" R
       WHERE  TF.PRO_ID = p_pro_id_in AND TF.MUN_ID = p_mun_id_in AND TF."YEAR" = p_year_in AND 
              M.CPRO = TF.PRO_ID AND M.CMUN = TF.MUN_ID AND 
              T.ID = TF.VTYPE_ID AND 
              R.VTYPE_ID = TF.VTYPE_ID AND R.VRANGE_ID = TF.VRANGE_ID;
  END;
/

  create or replace PROCEDURE "HR".GET_VTARIFFS_IDS_RS (p_pro_id_in IN NUMBER, p_mun_id_in IN NUMBER, p_year_in IN NUMBER, p_recordset OUT SYS_REFCURSOR)
   AS
   BEGIN
     OPEN p_recordset FOR
       SELECT TF.REG_ID, TF.PRO_ID, TF.MUN_ID, M.MUNICIPALITY, TF.VTYPE_ID, T.DESCRIPTION, TF.VRANGE_ID, R.DESCRIPTION, TF."YEAR", TF.PRICE, TF.CURRENCY
       FROM   "HR"."VT_TARIFFS" TF, "HR"."MUNICIPALITIES" M, "HR"."VTYPES"  T,  "HR"."VRANGES" R
       WHERE  TF.PRO_ID = p_pro_id_in AND TF.MUN_ID = p_mun_id_in AND TF."YEAR" = p_year_in AND 
              M.CPRO = TF.PRO_ID AND M.CMUN = TF.MUN_ID AND 
              T.ID = TF.VTYPE_ID AND 
              R.VTYPE_ID = TF.VTYPE_ID AND R.VRANGE_ID = TF.VRANGE_ID;
  END;
/